### PR TITLE
Simplistic enabling of LWIPv2 apps

### PR DESCRIPTION
**Pull request by malachib**
Nothing fancy, and shouldn't collide with existing code since most of the lwip/apps code requires explicit enablement

### CODE REVIEW

**Comment by ourairquality** [comment]
It seemed convenient to add the `$(LWIP_DIR)include/lwip/apps` to the `INC_DIRS` too. Building a httpd example seems to work fine using this approach. If it seems to be working ok after a little experience then I'll just bundle this into the lwip2 patch.

**Comment by malachib** [comment]
Great~ the `$(LWIP_DIR)include/lwip/apps` option makes me nervous.  I worry about header file collisions...I motion make everyone continue to explicitly include <lwip/apps/mdns.h> and friends

**Comment by ourairquality** [comment]
Ok, shall not change the include paths. An issue I saw quickly was easily fixed per-project.

**Comment by ourairquality** [comment]
Merge the PR into the esp-open-rtos lwip2 patch, thanks. btw also reduced the default stack to 768.

**Pull request closed without merging**
